### PR TITLE
Publish EventAny under its name

### PR DESCRIPTION
**Pull request by EPashkin**
To generate `Widget` signals `map-event` and `unmap-event` in https://github.com/gtk-rs/gtk/pull/339

### CODE REVIEW

**Comment by gkoz** [comment]
A hack like this just to make two signals automatic feels dubious.

**Comment by EPashkin** [comment]
Then what we do with 2 problem signals now?

**Comment by gkoz** [comment]
They can live in the manual widget trait, it's there anyway.

**Comment by EPashkin** [comment]
So only 2 signals in `WidgetSignals` :(

**Comment by gkoz** [comment]
I meant `WidgetExtManual` because I assume we're getting rid of all `*Signal` traits.

**Comment by EPashkin** [comment]
Ok that better that restoring it in `signals.rs`

**Pull request closed without merging**
