### PR TITLE
Add remaining GdkAtom constants

### LINKED ISSUE #120: Missing clipboard constants
As far as I can tell, this crate is missing bindings to the `GDK_SELECTION_CLIPBOARD`, `GDK_SELECTION_PRIMARY`, and `GDK_SELECTION_SECONDARY` constants. These constants are necessary to implement cut/copy/paste with GTK.

### PR DESCRIPTION
**Pull request by Susurrus**
Closes #120.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
Atom::None was reexported https://github.com/gtk-rs/gdk/blob/master/src/lib.rs#L74
and `mod atom` currently not public

**Comment by Susurrus** [comment]
@EPashkin How would you like these exported? Everything as `Atom::*` or should I re-export all these constants in the root?

**Comment by EPashkin** [comment]
As atom::None exported by different name I not sure :(

**Comment by EPashkin** [comment]
IMHO better just move all consts from atom.rs to lib.rs

**Comment by Susurrus** [comment]
What should be done about `Atom::None` then? And what should the final public exported names be?

**Comment by EPashkin** [comment]
IMHO ATOM_NONE better stay as is, and for other current names is good

**Comment by Susurrus** [comment]
If I move those constants out of `atom.rs` then I can't use the constructor. Should I just re-export them then or how should I organize this?

**Comment by EPashkin** [comment]
Your right. Then we have only one option: direct reexport under same name.
I don't see how it can be organized differently.

**Comment by Susurrus** [comment]
How about this?

**Comment by EPashkin** [comment]
👍 
Thanks, @Susurrus

**Comment by Susurrus** [comment]
This need anything else to be merged? Tests pass.

**Comment by GuillaumeGomez** [comment]
Just to ping me. ;)

Thanks!

**Pull request merged**
