### PR TITLE
Update GIR and regenerate/fixup everything

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gir/issues/480

### CODE REVIEW

**Comment by sdroege** [comment]
This failure is expected and needs https://github.com/gtk-rs/sys/pull/69 to be merged first.

**Comment by EPashkin** [comment]
Maybe it my local error on nightly, but `cargo build -vv` produce `error: [9/-3] object not found - no match for id (4f1cbb2ff643a585cee09d17c84994fb4ca43a56)`
without `-vv` it was just `error: An unknown error occurred`

**Comment by GuillaumeGomez** [comment]
Let's restart CI now then!

**Comment by GuillaumeGomez** [comment]
Worked fine. I merge then. Thanks!

**Comment by EPashkin** [comment]
My error was git related. Don't understand reason but many `git gc` and `git repack` helped.

**Comment by GuillaumeGomez** [comment]
That's a relief!

**Pull request merged**
