### PR TITLE
GString support

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by EPashkin** [comment]
Also problem on 1.28.0
```
  --> D:/eap/rust/0/gdk\src\atom.rs:38:26
   |
38 |     pub fn name(self) -> glib::GString {
   |                          ^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> D:/eap/rust/0/gdk\src\event_setting.rs:15:38
   |
15 |     pub fn get_name(&self) -> Option<glib::GString> {
   |                                      ^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> D:/eap/rust/0/gdk\src\keys.rs:10:43
   |
10 | pub fn keyval_name(keyval: u32) -> Option<glib::GString> {
   |                                           ^^^^

warning: unused import: `gobject_ffi`
  --> D:/eap/rust/0/gdk\src\event.rs:10:5
   |
10 | use gobject_ffi;
   |     ^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

```

**Comment by philn** [comment]
@EPashkin @GuillaumeGomez can you re-run CI for this?

**Comment by EPashkin** [comment]
Thanks and 👍

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
