### PR TITLE
Split out gdk-pixbuf

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz 

Needs [gdk-pixbuf's PR](https://github.com/gtk-rs/gdk-pixbuf/pull/2) to be merged before.

### CODE REVIEW

**Comment by gkoz** [comment]
The prelude build error suggests that the gdk-pixbuf needs its own, which could then be blanketly reexported in this crate's prelude.

**Comment by gkoz** [comment]
Or rather, let's not do the prelude reexport yet. I might prefer to do the reexporting once in gtk.

**Comment by GuillaumeGomez** [comment]
And updated as well (but the build won't work until gdk-pixbuf's PR is merged).

**Comment by GuillaumeGomez** [comment]
I restarted appveyor and travis.

**Comment by gkoz** [comment]
The appveyor build [has passed](https://ci.appveyor.com/project/GuillaumeGomez/gdk/build/1.0.68).

**Pull request merged**
