### PR TITLE
Remove traits for disguised types without children

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/760

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Is it ready or not yet? (Same question for all same PRs)

Otherwise the current code looks good to me.

**Comment by GuillaumeGomez** [comment]
Oh and the diff is failing.

**Comment by EPashkin** [comment]
It not ready because gir's part not merged.
As my PR is small I prefer merge it after your PR, @antoyo's and "edition2018",
to make full regen

**Comment by GuillaumeGomez** [comment]
Makes sense!

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
@EPashkin Can you reopen this PR please? I removed this commit by mistake (sorry). :-/

**Pull request merged**
