### PR TITLE
Cairo interactions: auto load Pixbuf & Surface Exts

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Part 1 of #308

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't understand the need for these changes, even after reading the issue...

**Comment by bilelmoussaoui** [comment]
Because its currently impossible to use those functions. Some need to be moved out Of the ContextExt which I want to send as a different PR

**Comment by GuillaumeGomez** [comment]
Even if you import the traits in your code? Can you show us an example with the problematic code please?

**Comment by bilelmoussaoui** [comment]
Without this patch I can't draw on a surface and restore the latest surface which is used on drawing user selected rectangle see https://gitlab.gnome.org/bilelmoussaoui/censor/blob/df8807078d50daf9aa3c2a631c0a4c1515a6d914/src/widgets/drawer.rs#L161 the code is a bit messy for now

**Comment by sdroege** [comment]
The change is correct, the traits must all be exported from the prelude like all other traits.

**Comment by GuillaumeGomez** [comment]
Makes sense indeed. Thanks @bilelmoussaoui !

**Comment by sdroege** [comment]
@GuillaumeGomez or @bilelmoussaoui can you create an issue here https://github.com/gtk-rs/gtk4/issues or a PR for doing the same change?

**Comment by bilelmoussaoui** [comment]
Will do.

**Pull request merged**
