### PR TITLE
Ignore thread_add and threads_add_timeout in favor of glibs analog

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gdk/issues/304

@sdroege Maybe instead ignoring we need fixing assert: https://developer.gnome.org/gdk3/stable/gdk3-Threads.html#gdk-threads-add-idle-full

cc @GuillaumeGomez

### CODE REVIEW

**Comment by sdroege** [comment]
> [](https://github.com/gtk-rs/gdk/issues/304)
> 
> @sdroege Maybe instead ignoring we need fixing assert: https://developer.gnome.org/gdk3/stable/gdk3-Threads.html#gdk-threads-add-idle-full

All GTK/GDK things are not thread-safe anyway and the example there is rather contrived. You can't do what is described there with safe Rust code with the bindings, and it's also unsafe to do in C on Windows and macOS at least.

**Comment by EPashkin** [comment]
@sdroege Thanks for the clarification

**Comment by sdroege** [comment]
Let's get this in then? @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
Thanks @EPashkin !

**Pull request merged**
