### PR TITLE
Install libmount-dev

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/pull/229

### CODE REVIEW

**Comment by EPashkin** [comment]
Error in cairo, also strange that win32surface compiled on linux

```
error[E0615]: attempted to take value of method `into` on type `enums::Format`
  --> /home/travis/.cargo/git/checkouts/cairo-e6055a6d391c3fc9/346fd93/src/win32_surface.rs:43:94
   |
43 |         unsafe { Self::from_raw_full(ffi::cairo_win32_surface_create_with_format(hdc, format.into)) }
   |                                                                                              ^^^^ help: use parentheses to call the method: `into()`
error: aborting due to previous error
```

**Comment by EPashkin** [comment]
Not fully fixed 😭 
```
error: incorrect close delimiter: `}`
  --> /home/travis/.cargo/git/checkouts/cairo-e6055a6d391c3fc9/f0183d0/src/win32_surface.rs:43:102
   |
43 |         unsafe { Self::from_raw_full(ffi::cairo_win32_surface_create_with_format(hdc, format.into()) }
   |                -                    - un-closed delimiter                                            ^ incorrect close delimiter
   |                |
   |                close delimiter possibly meant for this
```

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks for fixing cairo

**Comment by GuillaumeGomez** [comment]
Thanks for fixing CI. :p

**Pull request merged**
