### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Apply https://github.com/gtk-rs/gir/pull/419, https://github.com/gtk-rs/gir/pull/418 and appveyour version fix

### CODE REVIEW

**Comment by EPashkin** [comment]
cc @GuillaumeGomez, @sdroege

**Comment by sdroege** [comment]
:+1: thanks! Was going to do these today :) will you also do pango, gio, gtk or should I?

**Comment by GuillaumeGomez** [comment]
Finally! Thanks!

@sdroege: I can do pango and I leave you gio so the work is shared.

**Comment by sdroege** [comment]
Ok, I did pango. If you want, I can also do gio. Whatever you prefer :)

**Comment by GuillaumeGomez** [comment]
Leave me gio! :p

**Comment by sdroege** [comment]
Oh, I failed reading. You wanted pango :) Sorry! I'll leave you gio

**Comment by GuillaumeGomez** [comment]
I did, don't worry. :'(

**Pull request merged**
