### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/gtk-rs/sys/pull/152.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
We should figure out https://github.com/gtk-rs/atk/pull/42#discussion_r341996169 first.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by sdroege** [comment]
Good to go except for .travis.yml having to be updated to 1.39 (same for atk, sorry)

**Comment by sdroege** [comment]
:+1:

**Pull request merged**
