### PR TITLE
Add missing EventMotion function

### LINKED ISSUE #222: Bindings for gdk_event_request_motions() missing
GDK documentation: https://developer.gnome.org/gdk3/stable/gdk3-Events.html#gdk-event-request-motions

GTK 3.8 and onwards will always compress motion events, unless gdk_window_set_event_compression() is used to disable compression. gdk_event_request_motions() is the recommended way of decompressing the events in a handler, but it seems that the binding for it is missing. An alternative is the gdk_window_get_device_position() function, which does have a binding, but EventMotion doesn't seem to provide a .get_device() method on the Rust side.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #222.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
PR looks good itself, but strange, appveyor failing on gio.

**Comment by GuillaumeGomez** [comment]
That's super weird. O.o

**Comment by sdroege** [comment]
Unrelated to this PR, it's from the subprocess PR. For some reason it goes into the Unix code paths on Windows, so something needs to be changed there

This PR is fine and can be merged

**Comment by GuillaumeGomez** [comment]
Yes, I'm looking at the gio code right now trying to understand what's going on.

Thanks for reviews!

**Pull request merged**
