### PR TITLE
Separate Rectangle from cairo's

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
@gkoz Reexport `Rectangle` in `gtk`?

**Comment by gkoz** [comment]
:+1:

**Comment by EPashkin** [comment]
In generated code it will be `gdk::Rectangle` but for users IMHO better reexport it

**Comment by gkoz** [comment]
Reexporting makes sense.

**Comment by EPashkin** [comment]
Ping

**Comment by GuillaumeGomez** [comment]
Sorry for the delay. Thanks!

**Pull request merged**
