### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
@sdroege current output:

```
> cargo build
   Compiling gdk v0.9.0 (/Users/imperio/rust/gdk)
warning: unused import: `glib::object::IsA`
  --> src/auto/drag_context.rs:13:5
   |
13 | use glib::object::IsA;
   |     ^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `glib::Quark`
 --> src/auto/enums.rs:6:5
  |
6 | use glib::Quark;
  |     ^^^^^^^^^^^

warning: unused import: `glib::error::ErrorDomain`
 --> src/auto/enums.rs:9:5
  |
9 | use glib::error::ErrorDomain;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/auto/device.rs:343:83
    |
343 |                 Some(transmute(changed_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                   ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/device.rs:360:100
    |
360 |                 Some(transmute(notify_associated_device_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                                    ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/device.rs:377:93
    |
377 |                 Some(transmute(notify_input_mode_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                             ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/device.rs:385:89
    |
385 |                 Some(transmute(notify_n_axes_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                         ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/device.rs:411:87
    |
411 |                 Some(transmute(notify_type_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                       ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
  --> src/auto/device_manager.rs:51:88
   |
51 |                 Some(transmute(device_added_trampoline::<F> as usize)), Box_::into_raw(f))
   |                                                                                        ^ expected struct `std::boxed::Box`, found type parameter
   |
   = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
              found type `std::boxed::Box<F>`

error[E0308]: mismatched types
  --> src/auto/device_manager.rs:59:90
   |
59 |                 Some(transmute(device_changed_trampoline::<F> as usize)), Box_::into_raw(f))
   |                                                                                          ^ expected struct `std::boxed::Box`, found type parameter
   |
   = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
              found type `std::boxed::Box<F>`

error[E0308]: mismatched types
  --> src/auto/device_manager.rs:67:90
   |
67 |                 Some(transmute(device_removed_trampoline::<F> as usize)), Box_::into_raw(f))
   |                                                                                          ^ expected struct `std::boxed::Box`, found type parameter
   |
   = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
              found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/display.rs:366:82
    |
366 |                 Some(transmute(closed_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                  ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/display.rs:392:82
    |
392 |                 Some(transmute(opened_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                  ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
  --> src/auto/display_manager.rs:60:90
   |
60 |                 Some(transmute(display_opened_trampoline::<F> as usize)), Box_::into_raw(f))
   |                                                                                          ^ expected struct `std::boxed::Box`, found type parameter
   |
   = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
              found type `std::boxed::Box<F>`

error[E0308]: mismatched types
  --> src/auto/display_manager.rs:68:98
   |
68 |                 Some(transmute(notify_default_display_trampoline::<F> as usize)), Box_::into_raw(f))
   |                                                                                                  ^ expected struct `std::boxed::Box`, found type parameter
   |
   = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
              found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/screen.rs:273:94
    |
273 |                 Some(transmute(composited_changed_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                              ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/screen.rs:281:92
    |
281 |                 Some(transmute(monitors_changed_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                            ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/screen.rs:289:88
    |
289 |                 Some(transmute(size_changed_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                        ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/screen.rs:297:95
    |
297 |                 Some(transmute(notify_font_options_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                               ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
   --> src/auto/screen.rs:305:93
    |
305 |                 Some(transmute(notify_resolution_trampoline::<F> as usize)), Box_::into_raw(f))
    |                                                                                             ^ expected struct `std::boxed::Box`, found type parameter
    |
    = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
               found type `std::boxed::Box<F>`

error[E0308]: mismatched types
    --> src/auto/window.rs:1450:96
     |
1450 |                 Some(transmute(create_surface_trampoline::<Self, F> as usize)), Box_::into_raw(f))
     |                                                                                                ^ expected struct `std::boxed::Box`, found type parameter
     |
     = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
                found type `std::boxed::Box<F>`

error[E0308]: mismatched types
    --> src/auto/window.rs:1469:101
     |
1469 |                 Some(transmute(pick_embedded_child_trampoline::<Self, F> as usize)), Box_::into_raw(f))
     |                                                                                                     ^ expected struct `std::boxed::Box`, found type parameter
     |
     = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
                found type `std::boxed::Box<F>`

error[E0308]: mismatched types
    --> src/auto/window.rs:1482:95
     |
1482 |                 Some(transmute(notify_cursor_trampoline::<Self, F> as usize)), Box_::into_raw(f))
     |                                                                                               ^ expected struct `std::boxed::Box`, found type parameter
     |
     = note: expected type `std::boxed::Box<std::boxed::Box<(dyn std::ops::Fn() + 'static)>>`
                found type `std::boxed::Box<F>`

error: aborting due to 20 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `gdk`.

To learn more, run the command again with --verbose.
```

### CODE REVIEW

**Comment by sdroege** [comment]
This one needs a `cargo update`

**Comment by GuillaumeGomez** [comment]
Indeed, nevermind...

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Yes!

**Pull request merged**
