### PR TITLE
Reexport GdkRectangle

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks !
cc @gkoz

**Comment by gkoz** [comment]
The background: `GdkRectangle` is an alias of `cairo_rectangle_int_t`, which is reexported in `cairo` as `RectangleInt`. This crate reexports `RectangleInt` and uses it in the APIs in place of `GdkRectangle`.

That decision was made before the move to automation so it might not make as much sense now. We could reexport it as `Rectangle`. Which crate we reexport it from might not even make a difference, rustdoc will probably still link to `cairo_rectangle_int_t`.

**Comment by EPashkin** [comment]
@GuillaumeGomez seems direct reexport not good solution, do not merge this.

**Comment by GuillaumeGomez** [comment]
It seemed weird to me and I wanted @gkoz's opinion. So I close it.

**Pull request closed without merging**
