### PR TITLE
Missing parent

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, 👍 after CI.
But it have strange error on nightly, maybe it be fixed by restarting job

**Comment by GuillaumeGomez** [comment]
Weird indeed... I restarted it.

**Comment by EPashkin** [comment]
```
error[E0432]: unresolved import `gio_ffi`
 --> src/auto/app_launch_context.rs:9:5
  |
9 | use gio_ffi;
  |     ^^^^^^^ no `gio_ffi` in the root. Did you mean to use `glib_ffi`?
```

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Thanks for your reviews!

**Pull request merged**
