### PR TITLE
add missing GDK_EVENT_*

### LINKED ISSUE #336: Add GDK_EVENT_* & GDK_BUTTON_* to the public api
Per the discussion in that chat room

the gdk_button & gdk_event are exposed through the -sys crate only and should be part of the public API

Quoting ebassi

> There are a couple of defines that should be in the public API; like GDK_BUTTON_* and GDK_EVENT_PROPAGATE|STOP

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
I wonder though if we can make things a bit better?

closes #336

### CODE REVIEW

**Comment by sdroege** [comment]
Better how? We could use proper types (enums) for these things instead of `u32` inside the structs I guess, but that all has to be done manually.

**Comment by bilelmoussaoui** [comment]
I was wondering if we could have something like glib::Continue but that's too much work for now

**Comment by sdroege** [comment]
Agreed. That would be nicer :) Can you create an issue if you don't want to do it now?

**Comment by sdroege** [comment]
@GuillaumeGomez Good to go apart from the usual mac problems with travis.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
