### PR TITLE
Regenerate autogenerated bindings with latest GIR

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
IMHO still unneeded +IsA<Object> in device_manager, maybe others.

**Comment by sdroege** [comment]
Done, thanks!

**Comment by EPashkin** [comment]
@sdroege Thanks.
@GuillaumeGomez 👍 for this too

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
