### PR TITLE
Regenerate with latest gir

### PR DESCRIPTION
**Pull request by sdroege**
I'm not sure why there's no `ffi::gdk_event_get_type` though, which would otherwise be useful :) It's in the header at least

### CODE REVIEW

**Comment by EPashkin** [comment]
Maybe because `GdkEvent` is union?

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gir/pull/412

**Comment by sdroege** [comment]
Can be merged after https://github.com/gtk-rs/sys/pull/57

And the other regenerate PRs are also all ready and waiting :)

**Comment by EPashkin** [comment]
Need use gobject_ffi
```diff
--- a/src/event.rs
+++ b/src/event.rs
@@ -3,7 +3,8 @@
 // Licensed under the MIT license, see the LICENSE file or <http://opensource.org/licenses/MIT>
 
 use glib::translate::*;
-use ffi as ffi;
+use ffi;
+use gobject_ffi;
 
 use glib_ffi;
 use std::ptr;
```

**Comment by sdroege** [comment]
Thanks, done :)

**Comment by sdroege** [comment]
@GuillaumeGomez Good for merging IMHO :)

**Comment by GuillaumeGomez** [comment]
`./check_init_asserts` fails.

**Comment by sdroege** [comment]
Fixed, thanks

**Comment by sdroege** [comment]
Or better like this

**Comment by sdroege** [comment]
@GuillaumeGomez CI is happy now

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
