### PR TITLE
Add `dox` feature

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/pull/467

@GuillaumeGomez not fully tested as `cairo-sys-rs` don't builds on Windows due `x11` build script error on pkgconfig call.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Well, seems good. I can't check for now so if it breaks builds, it'll be time to fix. :p

**Comment by EPashkin** [comment]
.. but at minimum cairo-sys-rs/Cargo.toml need fix to document anyway.
I tried `dox = ["x11"]`

**Comment by EPashkin** [comment]
As I understand no way fix this error when build on Windows (`x11` uses https://github.com/joshtriplett/metadeps in build script and it can't be ignored).
So I hope that windows dependencies won't be problem.

**Comment by GuillaumeGomez** [comment]
I think it'll. Isn't cairo supposed to work on windows? :-/

**Comment by EPashkin** [comment]
It works, but `dox` feature activate functions with https://github.com/gtk-rs/cairo/blob/master/cairo-sys-rs/src/lib.rs#L541
so crate x11 also need activation or errors for undefined `xlib::*` appeared.

**Comment by EPashkin** [comment]
Added PR to X11 https://github.com/Daggerbot/x11-rs/pull/74

**Comment by GuillaumeGomez** [comment]
Is it good to go then?

**Comment by EPashkin** [comment]
For safety better wait while it merged and crated, next I need fix cairo to use it.
Or if current PR allow `cargo doc --features="dox embed-lgpl-docs"` normally on non windows you can merge it
and I start adding PRs for gtk and sourceview

**Comment by GuillaumeGomez** [comment]
Ok, once this one merged, I'll make a new release (unless you have other things you want to be merged first?).

**Comment by EPashkin** [comment]
Gtk, Sourceview need update before release, maybe pangocairo too (not sure how you planing build doc for it)

**Comment by GuillaumeGomez** [comment]
I'll make those updates then. For pangocairo, the docs are already available, no?

**Comment by EPashkin** [comment]
I forgot that it don't have features, then ignore pangocairo.

**Comment by EPashkin** [comment]
Hm, seems I forgot post this yesterday :(

For safety better wait while it merged and crated, next I need fix cairo to use it.
Or if current PR allow `cargo doc --features="dox embed-lgpl-docs"` normally on non windows you can merge it

**Comment by EPashkin** [comment]
Can be merged as x11 fixed and https://github.com/gtk-rs/cairo/pull/159 added.

**Pull request merged**
