### PR TITLE
Gir files zesty

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, restart build pls, may be now it build.

**Comment by GuillaumeGomez** [comment]
Done, let's see the output!

**Comment by EPashkin** [comment]
Now fail in gtk, so this ready

**Comment by GuillaumeGomez** [comment]
Great, let's move forward. Thanks!

**Comment by EPashkin** [comment]
Merge?

**Comment by GuillaumeGomez** [comment]
Too many of them, I'm lost!

**Pull request merged**
