### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/468

Apply https://github.com/gtk-rs/gir/pull/471, https://github.com/gtk-rs/gir/pull/467

cc @sdroege, @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
Will not pass test.
I will update https://github.com/gtk-rs/examples/pull/151 after this merged, It fails too,
then next regen for gtk will pass (seems even don't need merge https://github.com/gtk-rs/sys/pull/64 beforehand)

**Comment by sdroege** [comment]
Yes all regens are separate. You also do the others? Gtk, gio, glib, pango?

**Comment by EPashkin** [comment]
I plan only gtk and examples to make others compile.

**Comment by sdroege** [comment]
OK, I do the others later then. Thanks

**Comment by EPashkin** [comment]
@GuillaumeGomez please check this.

**Comment by GuillaumeGomez** [comment]
Ah finally, great! Thanks!

**Pull request merged**
