### PR TITLE
Don't box closures twice

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
What does that mean? :)

**Comment by sdroege** [comment]
> I don't know, probably old check_init_asserts(gtks check different names), or it bad with closures.

Ok but this is nothing new from my PR so let's worry about that another time :)

**Comment by EPashkin** [comment]
Agree.
We fails on new `event_handler_destroy` and `event_handler_trampoline` and want assert macro here.
Seems constraint broke regex

**Comment by sdroege** [comment]
@GuillaumeGomez good to go :)

**Pull request merged**
