### PR TITLE
Removed missed manual duplicate modifier_type

### PR DESCRIPTION
**Pull request by EPashkin**
Duplicate of generated https://github.com/gtk-rs/gdk/blob/master/src/auto/flags.rs#L184-L219

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Maybe also better move keys to it module and remove `src/enums.rs`?
Also it need fix in examples first

**Comment by GuillaumeGomez** [comment]
I don't have strong opinion on this. If what you propose is better, then no problem. ;)

**Comment by EPashkin** [comment]
@GuillaumeGomez I also not sure about need of move keys, so currently leave it in enums.

**Comment by GuillaumeGomez** [comment]
Fine by me.

**Pull request merged**
