### PR TITLE
Update for new `Value::get` signature

### PR DESCRIPTION
**Pull request by fengalin**
See gtk-rs/glib#513 & gtk-rs/gir#825

### CODE REVIEW

**Comment by fengalin** [comment]
Either we wait for https://github.com/gtk-rs/cairo/pull/281 to be merged and we relaunch CI to get rid of the error when running `cargo doc --features "dox,embed-lgpl-docs"`, or we merge this one and I go on with https://github.com/fengalin/gtk/tree/value_get_result.

**Comment by fengalin** [comment]
Either way, they interlock :)

**Comment by sdroege** [comment]
@GuillaumeGomez :+1:

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
